### ISSUE TITLE
MemoryError when train_lpcnet

### ISSUE THREAD

**Issue by candlewill** [mozilla/LPCNet#13]
I train the model on another dataset, the features size is : 

![image](https://user-images.githubusercontent.com/4916563/50129271-1cf91c00-02b3-11e9-90e1-6dd0028959b1.png)

It seems that all data is loaded into CPU memory. My machine has 100GB+ CPU memory, and 8GB GPU memory. I met the memory error, when do train_lpcnet.py.

```
lambda_1 (Lambda)               (None, None, 128)    0           feature_dense2[0][0]             
                                                                 feature_dense2[0][0]             
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, None, 512)    0           reshape_1[0][0]                  
                                                                 reshape_2[0][0]                  
                                                                 lambda_1[0][0]                   
__________________________________________________________________________________________________
gru_a (CuDNNGRU)                [(None, None, 384),  1034496     concatenate_2[0][0]              
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, None, 512)    0           gru_a[0][0]                      
                                                                 lambda_1[1][0]                   
__________________________________________________________________________________________________
gru_b (CuDNNGRU)                [(None, None, 16), ( 25440       concatenate_3[0][0]              
__________________________________________________________________________________________________
dual_fc (MDense)                (None, None, 256)    9216        gru_b[0][0]                      
==================================================================================================
Total params: 1,259,334
Trainable params: 1,259,334
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "./src/train_lpcnet.py", line 104, in <module>
    pred_in = ulaw2lin(in_data)
  File "/home/storage11/heyunchao/Torch_Programs/LPCNet/src/ulaw.py", line 11, in ulaw2lin
    return s*scale_1*(np.exp(u/128.*math.log(256))-1)
MemoryError
```

Could someone tell me what I am wrong?

**Comment by candlewill** [comment]
I rewrite `train_lpcnet.py` to use `model.fit_generator`, then problem solved.

If someone wants to use my modified version. I will create a pull request.

**Comment by candlewill** [comment]
If someone is in interest, here is the PR: https://github.com/mozilla/LPCNet/pull/15
