### ISSUE TITLE
overflow and InvalidArgumentError

### ISSUE THREAD

**Issue by xajdlg** [mozilla/LPCNet#141]
Total params: 1,239,904
Trainable params: 1,239,904
Non-trainable params: 0
__________________________________________________________________________________________________
ulaw std =  35.77564276809942
**_### ./training_tf2/train_lpcnet.py:95: RuntimeWarning: overflow encountered in multiply
  periods = (.1 + 50*features[:,:,36:37]+100).astype('int16')
./training_tf2/train_lpcnet.py:95: RuntimeWarning: invalid value encountered in multiply
  periods = (.1 + 50*features[:,:,36:37]+100).astype('int16')_**
Epoch 1/120
Traceback (most recent call last):
  File "./training_tf2/train_lpcnet.py", line 124, in <module>
    model.fit([in_data, features, periods], out_exc, batch_size=batch_size, epochs=nb_epochs, validation_split=0.0, callbacks=[checkpoint, sparsify])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[51,6,0] = 8352 is not in [0, 256)
         [[node model/embed_pitch/embedding_lookup (defined at ./training_tf2/train_lpcnet.py:124) ]] [Op:__inference_train_function_26980]

Errors may have originated from an input operation.
Input Source operations connected to node model/embed_pitch/embedding_lookup:
 model/embed_pitch/embedding_lookup/14692 (defined at /usr/lib/python3.6/contextlib.py:81)

**### the problem seem to be at the features created, but i create features of my own data by following the step on github,wav->pcm->concatenate->.f32 and .u8**

**Comment by jmvalin** [comment]
Check the range of the data you have as features[:,:,36:37]. If there's an overflow it means that the range is *very* wrong. Either you're passing the wrong file or something went really wrong in the feature computation.
