### ISSUE TITLE
new project version

### ISSUE THREAD

**Issue by wangshiyao-1119** [mozilla/LPCNet#165]
what tensorflow and keras version is needed for the new version of the project?
I tried tensorflow2.1.0+keras 2.3.1 , but  an error occurred：

Traceback (most recent call last):
  File "./training_tf2/train_lpcnet.py", line 125, in <module>
    model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics='sparse_cat
egorical_crossentropy')  File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co
re/python/training/tracking/base.py", line 457, in _method_wrapper    result = method(self, *args, **kwargs)
  File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co
re/python/keras/engine/training.py", line 429, in compile    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co
re/python/keras/engine/training.py", line 1842, in _cache_output_metric_attributes    metrics, self.output_names, output_shapes, self.loss_functions)
  File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co
re/python/keras/engine/training_utils.py", line 874, in collect_per_output_metric_info    'Expected a list or dictionary, found: ' + str(metrics))
TypeError: Type of `metrics` argument not understood. Expected a list or dictionary, found: 
sparse_categorical_crossentropy

Can someone answer it, thank you very much！！

**Comment by xiaochunxin** [comment]
> what tensorflow and keras version is needed for the new version of the project? I tried tensorflow2.1.0+keras 2.3.1 , but an error occurred：
> 
> Traceback (most recent call last): File "./training_tf2/train_lpcnet.py", line 125, in model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics='sparse_cat egorical_crossentropy') File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co re/python/training/tracking/base.py", line 457, in _method_wrapper result = method(self, *args, **kwargs) File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co re/python/keras/engine/training.py", line 429, in compile self._cache_output_metric_attributes(metrics, weighted_metrics) File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co re/python/keras/engine/training.py", line 1842, in _cache_output_metric_attributes metrics, self.output_names, output_shapes, self.loss_functions) File "/home/sywang/anaconda3/envs/projectlpcnet2/lib/python3.6/site-packages/tensorflow_co re/python/keras/engine/training_utils.py", line 874, in collect_per_output_metric_info 'Expected a list or dictionary, found: ' + str(metrics)) TypeError: Type of `metrics` argument not understood. Expected a list or dictionary, found: sparse_categorical_crossentropy
> 
> Can someone answer it, thank you very much！！

Did you find the correct version?

**Comment by wangshiyao-1119** [comment]
> I meet the version problem too!!!!!

I solved this problem~
correct version:
cuda10.1 + cudnn7.6.5 + tensorflow2.2.0 + keras 2.3.1

**Comment by Nishant19697** [comment]
> > I meet the version problem too!!!!!
> 
> I solved this problem~ correct version: cuda10.1 + cudnn7.6.5 + tensorflow2.2.0 + keras 2.3.1



> > I meet the version problem too!!!!!
> 
> I solved this problem~ correct version: cuda10.1 + cudnn7.6.5 + tensorflow2.2.0 + keras 2.3.1



> > I meet the version problem too!!!!!
> 
> I solved this problem~ correct version: cuda10.1 + cudnn7.6.5 + tensorflow2.2.0 + keras 2.3.1

i have installed the same versions but i am getting error while traning can you please help me out i am stucked here for so long unable to solve the issue
