### ISSUE TITLE
Bug in pitch embedding implementation

### ISSUE THREAD

**Issue by TheGrumpySnail01** [mozilla/LPCNet#84]
There is a bug in the pitch embedding implementation: The embedding layer is defined as

pembed = Embedding(256, 64, name='embed_pitch')

which expects values ranging from 0 to 255, but the maximal pitch value is 256.

Apparently, this does not cause an exception for tensorflow-gpu backend, but when
running the model with non-gpu tensorflow library, the model crashes (see output below).

One easy way to fix the problem is to feed pitch - PITCH_MIN_PERIOD to the model.

The following output was produced with a sawtooth signal with a pitch lag of 256:

Traceback (most recent call last):
  File "test_lpcnet.py", line 82, in <module>
    cfeat = enc.predict([features[c:c+1, :, :nb_used_features], periods[c:c+1, :, :]])
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/usr/local/anaconda3/envs/ki/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,1400,0] = 256 is not in [0, 256)

**Comment by zhangjh915** [comment]
Just add 1 to the embedding dimension and it should work. According to the Keras documentation, 0 is always reserved for padding and you can simply add 1 to shift the indices to the right. However, I am also curious why this would happen since this reservation should be turned off by default. Anyway, just add 1 to fix this issue.
